# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_truck', models.BooleanField(default=True)),
                ('truck_name', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_description', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('twitter_page', models.URLField(blank=True, null=True)),
                ('instagram_page', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=255, null=True)),
                ('specials', models.TextField(blank=True, null=True)),
                ('biz_id_yelp', models.CharField(blank=True, max_length=250, null=True)),
                ('menu_item_1', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_2', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_3', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_4', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_5', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_6', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_7', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_8', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_9', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_item_10', models.CharField(blank=True, max_length=255, null=True)),
                ('item_1_price', models.FloatField(blank=True, null=True)),
                ('item_2_price', models.FloatField(blank=True, null=True)),
                ('item_3_price', models.FloatField(blank=True, null=True)),
                ('item_4_price', models.FloatField(blank=True, null=True)),
                ('item_5_price', models.FloatField(blank=True, null=True)),
                ('item_6_price', models.FloatField(blank=True, null=True)),
                ('item_7_price', models.FloatField(blank=True, null=True)),
                ('item_8_price', models.FloatField(blank=True, null=True)),
                ('item_9_price', models.FloatField(blank=True, null=True)),
                ('item_10_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truck_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
