# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='truckprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='truckprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='trucklocation',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.TruckProfile'),
        ),
    ]
