# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckprofile',
            name='item_10_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_9_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
