# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20160509_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trucklocation',
            name='truck',
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TruckLocation',
        ),
    ]
