# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20160513_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckprofile',
            name='item_1_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_2_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_3_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_4_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_5_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_6_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_7_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='item_8_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
