# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20160510_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='yelp_biz_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
