# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_truckprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckprofile',
            name='profile',
        ),
    ]
