# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20160513_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='item_10_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_1_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_2_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_3_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_4_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_5_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_6_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_7_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_8_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='item_9_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
