# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_truckprofile_yelp_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='menu_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='truck_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
