# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0004_remove_truckprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='truck_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
