# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20160512_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckprofile',
            name='yelp_biz_id',
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='biz_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
