# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_truckprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='is_truck',
            field=models.BooleanField(default=True),
        ),
    ]
