# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_auto_20160512_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckprofile',
            old_name='biz_id',
            new_name='biz_id_yelp',
        ),
    ]
