# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_auto_20160512_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckprofile',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='menu_item_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
