language: python

python:
    - 3.5.3

services:
  - postgresql
  - memcached

env:
  - DJANGO=1.9.5
  - DJANGO=1.9.4

before_install:
  - export DJANGO_SETTINGS_MODULE=food_is_cool.travis-settings
  - export PYTHONPATH=$HOME/builds/davidbldogett/food_is_cool
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE foodiscool;" -U postgres
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test

after_success:
- coveralls
