# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='liked_truck',
            field=models.ManyToManyField(to='trucks.TruckProfile'),
        ),
    ]
