# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_liked_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='liked_truck',
            field=models.ManyToManyField(related_name='liked_truck', to='trucks.TruckProfile'),
        ),
    ]
