# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20160510_0959'),
        ('customers', '0003_auto_20160510_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='liked_truck',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='liked_trucks',
            field=models.ManyToManyField(to='trucks.TruckProfile'),
        ),
    ]
