# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20160510_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='liked_trucks',
            field=models.ManyToManyField(blank=True, to='trucks.TruckProfile'),
        ),
    ]
