# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_customerprofile_truckprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='truckprofile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='TruckProfile',
        ),
    ]
