# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('suite_number', models.TextField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zipcode', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('want_texts', models.BooleanField(default=False)),
                ('want_emails', models.BooleanField(default=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=12)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('suite_number', models.TextField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TruckProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('website', models.URLField(null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('twitter_page', models.URLField(null=True)),
                ('instagram_page', models.URLField(null=True)),
                ('logo_url', models.URLField(null=True)),
                ('cuisine', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
