# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='cuisine',
            field=models.CharField(default='old_value', max_length=255),
            preserve_default=False,
        ),
    ]
