# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckfinder', '0002_truckprofile_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckprofile',
            name='cuisine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='facebook_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='instagram_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='logo_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='twitter_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='truckprofile',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
