# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckfinder', '0003_auto_20160430_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='truck_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
