# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckfinder', '0004_truckprofile_truck_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='latitutde',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
