# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBlasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(blank=True, max_length=12, null=True)),
                ('from_number', models.CharField(blank=True, max_length=12, null=True)),
                ('text_content', models.TextField(blank=True, max_length=160, null=True)),
                ('media_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
