# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailblasts',
            name='to_email',
        ),
        migrations.RemoveField(
            model_name='smsnotifications',
            name='to_number',
        ),
    ]
