# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160507_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailblasts',
            name='to_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
