# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailblasts_to_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotifications',
            name='from_number',
        ),
    ]
