# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_smsnotifications_from_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotifications',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
